# Random Number Generation for JIT Compilation

[![Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/brainpy/brainpy/blob/master/docs_version2/tutorial_math/random_number_generation.ipynb)
[![Open in Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/brainpy/brainpy/blob/master/docs_version2/tutorial_math/random_number_generation.ipynb)

[Chaoming Wang](mailto:chao.brain@qq.com)

Although ``brainpy.math.random`` is designed to be seamlessly compatible with ``numpy.random``, there are still some differences under the context of JIT compilation.

In this section, we are going to talk about how to program a JIT-compatible code with ``brainpy.math.random``.

In [1]:
import brainpy as bp
import brainpy.math as bm
import numpy as np

# bm.set_platform('cpu')

/home/chaoming/miniconda3/envs/brainx/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
bp.__version__

'2.8.0'

## Using ``bm.random`` outside functions to JIT

Using ``brainpy.math.random`` outside of functions to JIT is the same as using ``numpy.random``.

This usage corresponds to the cases that generating random data for further processing. For example,

In [3]:
bm.random.rand(10)

Array([2.3681116e-01, 4.7876692e-01, 7.3578441e-01, 7.2716093e-01,
       1.1444092e-05, 5.0029898e-01, 7.7005649e-01, 6.5257323e-01,
       2.3098588e-01, 7.7129853e-01], dtype=float32)

In [4]:
np.random.rand(10)

array([0.00838137, 0.15910073, 0.67182281, 0.31307152, 0.08349506,
       0.41476039, 0.24424634, 0.16937301, 0.66186656, 0.70968565])

When you are using API functions in ``brainpy.math.random``, actually you are calling functions in a default ``RandomState``. Similarly, ``numpy.random`` also has a default ``RandomState``. Calling a random function in ``numpy.random`` module corresponds to calling the random function in this default NumPy ``RandomState``.

In [5]:
bm.random.DEFAULT

RandomState(Array((), dtype=key<fry>) overlaying:
[2453147516 3859196419])

## Using ``bm.random`` inside a function to JIT

If you are using random sampling in a JIT function, **there are things you need to pay attention to**. Otherwise, the error is likely to raise.

As I have stated above, ``brainpy.math.random`` functions are using the default ``RandomState``. A ``RandomState`` is an instance of brainpy [Variable](./arrays_and_variables.ipynb), denoting that it has values to change after calling any its built-in random function. What's changing is the `key` of a ``RandomState``. For instance,

In [6]:
bm.random.rand(1)
print('Now, the DEFAULT is', bm.random.DEFAULT)

Now, the DEFAULT is RandomState(Array((), dtype=key<fry>) overlaying:
[ 98774814 973971761])


In [7]:
bm.random.rand(1)
print('Now, the DEFAULT is', bm.random.DEFAULT)

Now, the DEFAULT is RandomState(Array((), dtype=key<fry>) overlaying:
[1786537643 3932128334])


Therefore, if you do not specify this DEFAULT ``RandomState`` you are using, repeatedly calling random functions in ``brainpy.math.random`` module will not get what you want, because its `key` cannot be updated. For instance,

In [8]:
@bm.jit
def get_data():
    return bm.random.random(2)

In [9]:
get_data()

Array([0.83370316, 0.52313995], dtype=float32)

In [10]:
get_data()

Array([0.1255579 , 0.84251523], dtype=float32)

A correct way is explicitly declaring you are using this DEFAULT variable in the JIT transformation.

In [11]:
bm.random.seed()

In [12]:
from functools import partial

@partial(bm.jit)
def get_data_v2():
    return bm.random.random(2)

In [13]:
get_data_v2()

Array([0.6613307 , 0.14987624], dtype=float32)

In [14]:
get_data_v2()

Array([0.74473476, 0.7490096 ], dtype=float32)

Or, declare the function as a `BrainPyObject`, then use ``jit()``.

In [15]:
@bm.jit
def get_data_v3():
    return bm.random.random(2)

In [16]:
get_data_v3()

Array([0.23168421, 0.4247079 ], dtype=float32)

In [17]:
get_data_v3()

Array([0.94978225, 0.64936876], dtype=float32)

## Using ``RandomState`` for objects to JIT

Another way I recommend is using instances of ``RandomState`` for objects to JIT. For example, you can initialize a ``RandomState`` in the ``__init__()`` function, then using the initialized ``RandomState`` anywhere.

In [18]:
class MyOb(bp.BrainPyObject):
    def __init__(self):
        super().__init__()
        self.rng = bm.random.RandomState(123)

    def __call__(self):
        size = (50, 100)
        u = self.rng.random(size)
        v = self.rng.uniform(size=size)
        z = bm.sqrt(-2 * bm.log(u)) * bm.cos(2 * bm.pi * v)
        return z

In [19]:
ob = bm.jit(MyOb())

In [20]:
ob()

Array([[ 1.7141678 , -0.9375559 , -1.5660878 , ..., -2.300819  ,
        -0.32444724, -1.0213778 ],
       [ 0.22194532,  0.8686901 , -1.8543271 , ...,  0.6031633 ,
         0.5587094 ,  0.17947507],
       [-0.04175869, -0.25695515,  0.41855374, ...,  0.7097617 ,
        -1.0369484 , -2.6332123 ],
       ...,
       [-0.5513834 , -1.2007083 , -0.21716705, ...,  2.4005718 ,
        -1.97702   , -1.9229665 ],
       [ 1.9620371 , -1.0303059 ,  0.50337774, ...,  1.0114168 ,
         0.5670819 ,  0.3017683 ],
       [-1.576822  , -1.2365927 ,  0.87836343, ..., -1.5918341 ,
         0.79131055, -1.8031497 ]], dtype=float32)

Note that any ``Variable`` instance which can be directly accessed by ``self.`` is able to be automatically found by brainpy's JIT transformation functions.
Therefore, in this case, we do not need to pass the ``rng`` into the `dyn_vars` in ``bm.jit()`` function.